# Generated by Django 4.2.7 on 2025-08-21 10:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Surname in BLOCK LETTERS', max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(help_text='Age at time of application', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('region_of_birth', models.CharField(max_length=100)),
                ('home_town', models.CharField(max_length=100)),
                ('region_of_home_town', models.CharField(max_length=100)),
                ('last_school_attended', models.CharField(blank=True, max_length=200, null=True)),
                ('location_of_last_school', models.CharField(blank=True, max_length=200, null=True)),
                ('class_before_admission', models.CharField(help_text='Class/Stage before admission', max_length=50)),
                ('religious_denomination', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies', models.TextField(blank=True, help_text="Child's hobbies or interests", null=True)),
                ('disability_or_allergy', models.TextField(blank=True, help_text='State any disability or allergy', null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('postal_address', models.TextField()),
                ('place_of_residence', models.CharField(max_length=200)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for the application', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
